### PR TITLE
Integrated Coreference Resolution

### PR DESCRIPTION
**Pull request by lxucs**

### CODE REVIEW

**Review by hankcs — CHANGES_REQUESTED** [review]
Coref models seems not playing well with pre-tokenized tokens specified in [data-format](https://github.com/emorynlp/elit/blob/main/docs/data_format.md#input-format).

```python
>>> from elit.client import Client
>>> nlp = Client('http://0.0.0.0:8000')
>>> tokens = [
...         ["Emory", "NLP", "is", "a", "research", "lab", "in", "Atlanta", ",", "GA", "."],
...         ["It", "is", "founded", "by", "Jinho", "D.", "Choi", "in", "2014", ".", "Dr.", "Choi", "is", "a", "professor",
...          "at", "Emory", "University", "."]
...     ]
>>> nlp.parse(tokens=tokens, models=['dcr'], verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hhe43/elit/elit/client.py", line 28, in parse
    'verbose': verbose
  File "/home/hhe43/elit/elit/client.py", line 37, in _send_post_json
    return json.loads(self._send_post(url, form))
  File "/home/hhe43/elit/elit/client.py", line 34, in _send_post
    return urlopen(request).read().decode()
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/hhe43/.local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by lxucs** [comment]
The model has no problem with the pre-tokenized tokens and it can be run successfully by local tests ([test_service_coref_doc.py](https://github.com/emorynlp/elit/blob/liyan/tests/test_service_coref_doc.py)). I also added examples in [client.py](https://github.com/emorynlp/elit/blob/liyan/elit/client.py) for usage of both document-coref and online-coref.
The issue is likely from the server setting/processing; even the original code without coref is having trouble passing the client tests. You might have the latest code so you can test on your side.

**Comment by lxucs** [comment]
One thing I did find is that I had different output format; I have made the output format changes accordingly, and updated the README in docs.

**Comment by hankcs** [comment]
I'm sorry but your new update didn't work out. Could you make a unitest for the 3 formats as I did in this file?

https://github.com/emorynlp/elit/blob/feab4f3994ec900072a8f45eab47e87a63a5624e/tests/test_joint_model.py

You might also want to put the unittest into travis config:

https://github.com/emorynlp/elit/blob/main/.travis.yml#L17

**Comment by hankcs** [comment]
The CI is back to normal now. Once the unittest passed CI like this [one](https://travis-ci.com/github/emorynlp/elit/builds/210580241), then we can merge it.

**Comment by lxucs** [comment]
I will close this PR and create a new PR in another branch.

**Pull request closed without merging**
